spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
    hibernate:
      ddl-auto: update
    show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    root: error