server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: local
    group:
      local: logging-type-console, logging-level-local
      dev: logging-type-file, logging-level-dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        ddl-auto: update  # Apply schema chang on real database, not for production level database
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
    hibernate:
      ddl-auto: update
    show_sql: true
    open-in-view: true

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n" # form of printing log
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
    root: error
